### ISSUE TITLE
"Névjegyek" navbar element displayed as "a:hover"

### ISSUE THREAD

**Issue by mattie404** [xdmanus1/the-physics-game#1]
In style.css line 34 `a:hover { [...]` if you add the id of myBtn the text will be shown when the user's cursor is on the text.
No clue how to fix coz if you remove the id from the css then it won't change the color and won't underline.
![image](https://github.com/xdmanus1/the-physics-game/assets/145768219/e738f4ea-ebaa-45f2-9dba-ad2d094cef38)

**Comment by xdmanus1** [comment]
fix: a:hover myBtn:hover
